---
title: "A20"
author: "Guoxin Chen"
date: "4/9/2019"
output:
  pdf_document: default
  html_document: default
---
#A20
```{r}
library(readxl) 
library(readr) 
library(arules) 
library(arulesViz) 
library(tibble)
library(readxl)

t <- read_excel("/Users/apple/Assignment/Dataset/Sample - Superstore.xls")
path = "Assignment/Dataset/Sample - Superstore.xls"
t1 <- tibble(orderID=t$`Order ID`,productName=t$`Product Name`)

library(readr)
write_csv(t1,'transactions.csv')
models <- read.transactions(file = "transactions.csv",
sep=",", format = 'single', cols = c(1,2)) 
LIST(head(models))
```
```{r}
library(arules)
library(arulesViz)
Appa20 <- apriori (models, parameter = list(supp = 0.0005, conf = .8, maxlen = 3))
```
```{r}
conf <- sort (Appa20 , by="confidence", decreasing=TRUE)
inspect(head(conf))
```

Our Analysis:
since our confidence is 1 and our lift is 744, we can conclude that the Anker Atro Mini charger and Bretford Furniture are frequently bought together. we suggest putting these two items in a package deal to promote further sales.